name: WhereFam
include:
  - app/addons/addons.yml

packages:
  ConcentricOnboarding:
    url: https://github.com/exyte/ConcentricOnboarding.git
    from: 1.0.6
  BareKit:
    url: https://github.com/holepunchto/bare-kit-swift
    branch: main
  swiftui-dsl:
    url: https://github.com/maplibre/swiftui-dsl
    branch: main
  purchases-ios-spm:
    url: https://github.com/RevenueCat/purchases-ios
    from: 5.34.0

targets:
  App:
    type: application
    platform: iOS
    deploymentTarget: 17
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wherefam.ios
        SWIFT_VERSION: 5.0
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
        CODE_SIGN_STYLE: Automatic

    info:
      path: app/Info.plist
      properties:
        NSLocationWhenInUseUsageDescription: We would like to access location for sharing to other members
        NSLocationAlwaysAndWhenInUseUsageDescription: We would like to access location for sharing to other members
        UILaunchScreen: app/Assets.xcassets/AppIcon.appIconset
        UIBackgroundModes:
          - location
    entitlements:
      path: app/WhereFam.entitlements
      properties:
        aps-environment: development
        com.apple.security.application-groups:
          - group.com.wherefam.ios

    capabilities:
      - inAppPurchase: true
      - pushNotifications: true 

    appIcon: app/Assets.xcassets/AppIcon.appIconset
    dependencies:
      - package: ConcentricOnboarding
      - package: BareKit
      - framework: app/frameworks/BareKit.xcframework
      - target: NotificationServiceExtension
      - package: swiftui-dsl
        product: MapLibreSwiftDSL
        product: MapLibreSwiftUI
      - package: purchases-ios-spm
        product: RevenueCat

    sources:
      - path: app/App.swift
      - path: app/AppDelegate.swift
      - path: app/app.bundle
      - path: app/Assets.xcassets
      - path: app/NotificationService.swift
      - path: app/push.bundle
      - path: app/style.json
      - path: app/WhereFam.storekit

      - path: app/Core/Root/ContentView.swift
        group: app/Core/Root

      - path: app/Core/Home/View/PeopleView.swift
        group: app/Core/Home/View
      - path: app/Core/Home/View/HomeView.swift
      - path: app/Core/Home/View/ProvideFeedbackView.swift
      - path: app/Core/Home/View/ShareIDView.swift
      - path: app/Core/Home/View/SupportAppView.swift

      - path: app/Core/Onboarding/View/FifthPageView.swift
        group: app/Core/Onboarding/View
      - path: app/Core/Onboarding/View/FirstPageView.swift
      - path: app/Core/Onboarding/View/FourthPageView.swift
      - path: app/Core/Onboarding/View/SecondPageView.swift
      - path: app/Core/Onboarding/View/SixthPageView.swift
      - path: app/Core/Onboarding/View/ThirdPageView.swift

      - path: app/Core/IPC/IPCViewModel.swift
        group: app/Core/IPC
      - path: app/Core/IPC/Worker.swift

      - path: app/js/app.js
        group: app/js
      - path: app/js/push.js
      - path: app/js/constants.js
      - path: app/js/hyperbee-manager.js
      - path: app/js/hyperswarm-manager.js
      - path: app/js/map-manager.js
      - path: app/js/ipc.js

      - path: app/Manager/LocationManager.swift
        group: app/Manager

      - path: app/Models/People.swift
        group: app/Models

    scheme:
      preActions:
        - name: Link
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-link" \
              --target ios-arm64 \
              --target ios-arm64-simulator \
              --target ios-x64-simulator \
              --out ${PWD}/app/addons \
              ${PWD}
        - name: Pack
          script: |
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --target ios-arm64 \
              --target ios-arm64-simulator \
              --target ios-x64-simulator \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app/app.bundle \
              ${PWD}/app/js/app.js
            PATH="${PATH}" "${PWD}/node_modules/.bin/bare-pack" \
              --target ios-arm64 \
              --target ios-arm64-simulator \
              --target ios-x64-simulator \
              --linked \
              --base ${PWD} \
              --out ${PWD}/app/push.bundle \
              ${PWD}/app/js/push.js

  NotificationServiceExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: 17.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wherefam.ios.NotificationServiceExtension
        SWIFT_VERSION: 5.0
    info:
      path: app/NotificationServiceExtension.Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.usernotifications.service
          NSExtensionPrincipalClass: NotificationServiceExtension.NotificationService
    entitlements:
      path: app/NotificationServiceExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.wherefam.ios
        # com.apple.developer.usernotifications.filtering: true
    dependencies:
      - framework: app/frameworks/BareKit.xcframework
      - package: BareKit
    sources:
      - path: app/NotificationService.swift
      - path: app/js/push.js
      - path: app/push.bundle
        optional: true
